"""add school_wide instructors flag and task support staff

Revision ID: 09b66febabdf
Revises: 9f1c198e8119
Create Date: 2026-08-21 12:51:32.655513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b66febabdf'
down_revision: Union[str, None] = '9f1c198e8119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_support_staff',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'instructor_id')
    )
    op.add_column(
        'instructors',
        sa.Column('school_wide', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'school_wide')
    op.drop_table('task_support_staff')
    # ### end Alembic commands ###
