"""add title and phone to instructors

Revision ID: 9f1c198e8119
Revises: 8055e0493511
Create Date: 2026-08-21 12:32:55.248179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1c198e8119'
down_revision: Union[str, None] = '8055e0493511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('instructors', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'phone')
    op.drop_column('instructors', 'title')
    # ### end Alembic commands ###
